# 开发环境配置文件
# 继承基础配置，覆盖开发环境特定设置

# 应用程序配置
app:
  name: "HXL Cloud (Development)"
  env: "development"
  debug: true
  port: 8080

# 数据库配置 - 开发环境
database:
  host: "localhost"
  port: 3306
  username: "dev_user"
  password: "dev_password"
  dbname: "hxl_cloud_dev"
  max_idle_conns: 5
  max_open_conns: 20

# Redis配置 - 开发环境
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 1  # 使用不同的数据库

# JWT配置 - 开发环境
jwt:
  secret: "dev-jwt-secret-key-change-in-production"
  expire_time: 86400  # 24小时，开发环境延长有效期

# 日志配置 - 开发环境
log:
  level: "debug"
  format: "text"  # 开发环境使用文本格式便于阅读
  output: "stdout"

# 文件存储配置 - 开发环境
storage:
  type: "local"
  local:
    upload_path: "uploads/dev"
    max_size: 52428800  # 50MB，开发环境放宽限制

# 邮件配置 - 开发环境（使用测试邮箱）
email:
  smtp_host: "localhost"
  smtp_port: 1025  # MailHog 测试邮件服务器
  username: ""
  password: ""
  from_email: "dev@hxlcloud.local"

# 限流配置 - 开发环境
rate_limit:
  enabled: false  # 开发环境关闭限流

# CORS配置 - 开发环境
cors:
  allowed_origins: ["http://localhost:3000", "http://localhost:8080", "http://127.0.0.1:3000"]
  allow_credentials: true

# 监控配置 - 开发环境
monitoring:
  enabled: true
  metrics_path: "/dev/metrics"
  health_path: "/dev/health"