# 生产环境配置文件
# 继承基础配置，覆盖生产环境特定设置

# 应用程序配置
app:
  name: "HXL Cloud"
  env: "production"
  debug: false
  port: 8080

# 数据库配置 - 生产环境
database:
  host: "${DB_HOST}"
  port: 3306
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  database: "${DB_DATABASE}"
  max_idle_conns: 20
  max_open_conns: 100
  conn_max_lifetime: 3600s

# Redis配置 - 生产环境
redis:
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  pool_size: 20
  min_idle_conns: 10

# JWT配置 - 生产环境
jwt:
  secret: "${JWT_SECRET}"
  expire_time: 3600  # 1小时
  refresh_expire_time: 604800  # 7天

# 日志配置 - 生产环境
log:
  level: "info"
  format: "json"
  output: "file"
  file_path: "/var/log/hxl-cloud/app.log"
  max_size: 100
  max_backups: 30
  max_age: 90
  compress: true

# 文件存储配置 - 生产环境
storage:
  type: "${STORAGE_TYPE}"  # oss, s3
  oss:
    endpoint: "${OSS_ENDPOINT}"
    access_key_id: "${OSS_ACCESS_KEY_ID}"
    access_key_secret: "${OSS_ACCESS_KEY_SECRET}"
    bucket_name: "${OSS_BUCKET_NAME}"
    domain: "${OSS_DOMAIN}"
  s3:
    region: "${S3_REGION}"
    access_key: "${S3_ACCESS_KEY}"
    secret_key: "${S3_SECRET_KEY}"
    bucket: "${S3_BUCKET}"
    endpoint: "${S3_ENDPOINT}"

# 邮件配置 - 生产环境
email:
  smtp_host: "${SMTP_HOST}"
  smtp_port: 587
  username: "${SMTP_USERNAME}"
  password: "${SMTP_PASSWORD}"
  from_email: "${SMTP_FROM_EMAIL}"
  from_name: "HXL Cloud"

# 限流配置 - 生产环境
rate_limit:
  enabled: true
  requests_per_minute: 100
  burst: 20

# CORS配置 - 生产环境
cors:
  allowed_origins: ["${FRONTEND_URL}"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE"]
  allowed_headers: ["Content-Type", "Authorization"]
  allow_credentials: true
  max_age: 86400

# 监控配置 - 生产环境
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/health"

# 第三方服务配置 - 生产环境
third_party:
  wechat:
    app_id: "${WECHAT_APP_ID}"
    app_secret: "${WECHAT_APP_SECRET}"
  alipay:
    app_id: "${ALIPAY_APP_ID}"
    private_key: "${ALIPAY_PRIVATE_KEY}"
    public_key: "${ALIPAY_PUBLIC_KEY}"
  sms:
    provider: "${SMS_PROVIDER}"
    access_key: "${SMS_ACCESS_KEY}"
    secret_key: "${SMS_SECRET_KEY}"
    sign_name: "${SMS_SIGN_NAME}"