# 应用配置文件
app:
  name: "ycg_cloud"
  version: "1.0.0"
  env: "development"  # development, testing, production
  debug: true
  timezone: "Asia/Shanghai"

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  read_timeout: 60s
  write_timeout: 60s
  max_header_bytes: 1048576  # 1MB

# 数据库配置
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: ""  # 从环境变量获取
  dbname: "ycg_cloud"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s
  log_level: "info"  # silent, error, warn, info

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""  # 从环境变量获取
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# JWT配置
jwt:
  secret: ""  # 从环境变量获取
  expire_time: 7200s  # 2小时
  refresh_expire_time: 604800s  # 7天
  issuer: "ycg_cloud"

# 日志配置
log:
  level: "info"  # debug, info, warn, error, fatal, panic
  format: "json"  # json, text
  output: "file"  # console, file, both
  file_path: "logs/app.log"
  max_size: 100  # MB
  max_age: 30    # days
  max_backups: 10
  compress: true

# 文件上传配置
upload:
  max_size: 10485760  # 10MB
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
    - "text/plain"
  upload_path: "uploads/"
  url_prefix: "/static/uploads/"

# CORS配置
cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 86400  # 24小时

# 限流配置
rate_limit:
  enabled: true
  requests_per_minute: 100
  burst: 200

# 缓存配置
cache:
  default_expiration: 3600s  # 1小时
  cleanup_interval: 600s     # 10分钟